travis:
  secure:
    BINSTAR_TOKEN: pktlas1hyKq/XMhiGvPJGBXGEIX0M17XBCIkbxUQfvBz+hUcmDH0CCjB2hYrckQ3eFz3mKf69vhYJLiSFZet4b47ClFDdzcBToE0IZMwyVeAjHzMAsZveDz+QdsDv+XqCN+fEyTJ1Izx1dGjfBOHNDZhWiNTfVtZiWi23JKsoeYDh0c8G20EvAM3wFYMW2QexyYnrXPn19HKUbO3qHf9qn3x4LbttuCFvE3UYvxQGNHt5YEPqDtMXITj77BnD7ApnYAn9MTMVJ8shnq24VV70S7U5bAwcOr/bOLXE9s0JeEce5UHA/HmBOeZTFF/M9K+VAKccAUgnecNByUBYq4rjKOx/M+LF73SBecnBFMiqeEgANshWgF54XBfAhYMQ3caxaR1roRnv2govv9vpH2v/ewJna7hhzoDstm3lOGgzLBjxtr4/mNbaOq+QMZ9iv8bJLT3dsTa9uDKgNir8e5HSPYBZXk4vU6K8oZPgsuYUR/Z7wEtiks5bSDxD584f+s7+7K6VNIa04iRZ2YE8HJ2aeoRrDOqpD6trS1xg+GyB9NitpN4DJF+KRdGOzCODFPFWKFuz5OMKmw/Uqp8k278urpkHk7bLMwwnCSioh51wAh7DsEUj10IBxGk1z7hvCVC7ejxkUol0Qq63E85sBebVlpC2GO/b6mHD6cGuKWGB4E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
