travis:
  secure:
    BINSTAR_TOKEN: bKdYEvb9dcGY8ueiN31gslLwYuzLIYyoLYGO0mpv1UZQyjB3mMKdQBqSeccw+2YYjtvL0Hic0+FiDqYehtOuUftc+lAx1PpBTeLPLSxjdxtFwc4El8riZMt50iUNMGYXau3+FjevONEt5K1S8LyG1y/k+ENmo/shkdRHnfTKoQxMKwP5Nvt/6o6QAqEUBYeVXaQK+cSrMeJOCkX81cqEmpNeJX6/WsFRhq7nqTxpacacqJ35u+/wJSgcEyRbFgEiy5O4YgZiuu6nBifAJbRz1w56pRi8o1yw0ti8N67+MLwRH0kVrq3ZmJMFR0LQlI2/mMWmHi1F81XbkmLyyeh7Oyeh9QcF+gONtyoc3QzKp3ht5cN2WaFO8hbFS/qc9ArtD8xhcauexDOQL0nCZouOvWJT8+fGyaFsSEglmtAlFcMdSKWIcvMdqdine1JgSvHrajQ4FoqXZlLvJtyKRxfd63yXc/E8DP5wA5Tq7jDTUaNSzhwCQrRIKibUcoRjSMLmzc92mRLoQ47m9R+Gh3RhPq3YKzqo9wtQSH7ykz4Ln8iRRAn3gqvEX4lDCC9d/AIeqS0e6FVIUsDBzVzmTPdK+sxLjFotZEy+THh4FTmXvpqmSHYScTllYVRLoU2KleDMz5lHNJ2L9Eo7IuRSGoA3y41FDyi7tfD+Abask6TlFJA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
